### ISSUE TITLE
Improvement: Usage of logger instead of print

### ISSUE THREAD

**Issue by sboett-dev** [eclipse-kuksa/kuksa-python-sdk#25]
This Python package includes several `print` statements, e.g. [here](https://github.com/eclipse-kuksa/kuksa-python-sdk/blob/main/kuksa-client/kuksa_client/cli_backend/grpc.py#L271). It is not possible to set the logging level.

It would be nice to be able to set the usual logging levels: `critical`, `error`, `warning`, `info`, `debug`.

## Example
During implementations with multiple connects and disconnects, the console gets spammed with
```
gRPC channel disconnected.
gRPC channel connected.
gRPC channel disconnected.
gRPC channel connected.
gRPC channel disconnected.
gRPC channel connected.
```

Thanks!

**Comment by SebastianSchildt** [comment]
Good point. We will come around to this eventually. Meanwhile of course, PRs welcome. I assume, the standard logging module (https://docs.python.org/3/library/logging.html)  would be the preferred solution

**Comment by erikbosch** [comment]
We already use `logging` in some downstream projects like

https://github.com/eclipse-kuksa/kuksa-can-provider/blob/main/dbcfeeder.py
https://github.com/eclipse-kuksa/kuksa-dds-provider/blob/main/ddsprovider.py

Also in the "library parts" of the package we often already use logging.

https://github.com/eclipse-kuksa/kuksa-python-sdk/blob/main/kuksa-client/kuksa_client/grpc/__init__.py

So I think it is mostly the CLI-parts that use print, but it would indeed be good to integrate the logging framework there as well. One could discuss if we should add logging formatting to this repo, so that for example we can remove `ColorFormatter` from https://github.com/eclipse-kuksa/kuksa-can-provider/blob/main/dbcfeeder.py#L101 and instead have it as a `KuksaDefaultFormatter` that all providers and the CLI could use.

**Comment by erikbosch** [comment]
I will make an attempt on fixing this one
